#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_UP,
	PLAYER_IDLE_DOWN,
	PLAYER_IDLE_LEFT,
	PLAYER_IDLE_RIGHT,	
	PLAYER_RUN_UP,
	PLAYER_RUN_DOWN,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_CLOSE_ATTACK,
	NUM_OF_PLAYER_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/